### ISSUE TITLE
Setting working directory in install_on_local.sh

### ISSUE THREAD

**Issue by phusen** [kuixu/alphafold#12]
The script `install_on_local.sh` sets the variable `work_path` to `$(PWD)`. In bash, this tries to run the command `PWD`, which usually doesn't exist. I believe, it should be `$PWD`, `${PWD}` or `$(pwd)`.

https://github.com/kuixu/alphafold/blob/21530fa4783d3e876df83f2596d1306cfbe0c98f/install_on_local.sh#L24

Also, ideally, some quotes should probably be added to support people running this in paths with spaces, eg:
```
# work_path=/path/to/alphafold-code
work_path="$PWD"
# update openmm 
a="$(which python)"
cd "$(dirname "$(dirname "$a")")/lib/python3.8/site-packages"
patch -p0 < "$work_path/docker/openmm.patch"
```

**Comment by kuixu** [comment]
Approved. Thanks for your contribution.
